import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Counter from "@/components/counter";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          これはルートレイアウト (src/app/layout.tsx)
          です。すべてのページに適用されます。ページをリロードするまで、ステートが保持されます。
        </div>
        <details>
          <summary>クリックしてやることリストを開く</summary>
          <ol>
            <li>
              <Link href="/items">青果の通販ページ</Link>を開く
            </li>
            <li>売れ筋商品を見る</li>
            <li>お買い物のヒントを見る</li>
            <li>成果を X でみんなに知らせる</li>
            <li>Next.js について、もっと深く学んでみる</li>
          </ol>
        </details>
        <Counter />
        <div>{children}</div>
      </body>
    </html>
  );
}
